steps:
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'mvn'
    args: ['clean', 'package']
    dir: './'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld', '.']

  - name: 'g