steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['package']
    dir: './'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helloworld']
images:
  - 'gcr.io/$PROJECT_ID/helloworld'